// This file was generated by counterfeiter
package unversionedfakes

import (
	"sync"

	"k8s.io/kubernetes/pkg/api"
	"k8s.io/kubernetes/pkg/client/unversioned"
	"k8s.io/kubernetes/pkg/watch"
)

type FakeReplicationControllerInterface struct {
	ListStub        func(opts api.ListOptions) (*api.ReplicationControllerList, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct {
		opts api.ListOptions
	}
	listReturns struct {
		result1 *api.ReplicationControllerList
		result2 error
	}
	GetStub        func(name string) (*api.ReplicationController, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		name string
	}
	getReturns struct {
		result1 *api.ReplicationController
		result2 error
	}
	CreateStub        func(ctrl *api.ReplicationController) (*api.ReplicationController, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		ctrl *api.ReplicationController
	}
	createReturns struct {
		result1 *api.ReplicationController
		result2 error
	}
	UpdateStub        func(ctrl *api.ReplicationController) (*api.ReplicationController, error)
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		ctrl *api.ReplicationController
	}
	updateReturns struct {
		result1 *api.ReplicationController
		result2 error
	}
	UpdateStatusStub        func(ctrl *api.ReplicationController) (*api.ReplicationController, error)
	updateStatusMutex       sync.RWMutex
	updateStatusArgsForCall []struct {
		ctrl *api.ReplicationController
	}
	updateStatusReturns struct {
		result1 *api.ReplicationController
		result2 error
	}
	DeleteStub        func(name string) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		name string
	}
	deleteReturns struct {
		result1 error
	}
	WatchStub        func(opts api.ListOptions) (watch.Interface, error)
	watchMutex       sync.RWMutex
	watchArgsForCall []struct {
		opts api.ListOptions
	}
	watchReturns struct {
		result1 watch.Interface
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeReplicationControllerInterface) List(opts api.ListOptions) (*api.ReplicationControllerList, error) {
	fake.listMutex.Lock()
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
		opts api.ListOptions
	}{opts})
	fake.recordInvocation("List", []interface{}{opts})
	fake.listMutex.Unlock()
	if fake.ListStub != nil {
		return fake.ListStub(opts)
	} else {
		return fake.listReturns.result1, fake.listReturns.result2
	}
}

func (fake *FakeReplicationControllerInterface) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeReplicationControllerInterface) ListArgsForCall(i int) api.ListOptions {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return fake.listArgsForCall[i].opts
}

func (fake *FakeReplicationControllerInterface) ListReturns(result1 *api.ReplicationControllerList, result2 error) {
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 *api.ReplicationControllerList
		result2 error
	}{result1, result2}
}

func (fake *FakeReplicationControllerInterface) Get(name string) (*api.ReplicationController, error) {
	fake.getMutex.Lock()
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		name string
	}{name})
	fake.recordInvocation("Get", []interface{}{name})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(name)
	} else {
		return fake.getReturns.result1, fake.getReturns.result2
	}
}

func (fake *FakeReplicationControllerInterface) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeReplicationControllerInterface) GetArgsForCall(i int) string {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].name
}

func (fake *FakeReplicationControllerInterface) GetReturns(result1 *api.ReplicationController, result2 error) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *api.ReplicationController
		result2 error
	}{result1, result2}
}

func (fake *FakeReplicationControllerInterface) Create(ctrl *api.ReplicationController) (*api.ReplicationController, error) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		ctrl *api.ReplicationController
	}{ctrl})
	fake.recordInvocation("Create", []interface{}{ctrl})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(ctrl)
	} else {
		return fake.createReturns.result1, fake.createReturns.result2
	}
}

func (fake *FakeReplicationControllerInterface) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeReplicationControllerInterface) CreateArgsForCall(i int) *api.ReplicationController {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].ctrl
}

func (fake *FakeReplicationControllerInterface) CreateReturns(result1 *api.ReplicationController, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 *api.ReplicationController
		result2 error
	}{result1, result2}
}

func (fake *FakeReplicationControllerInterface) Update(ctrl *api.ReplicationController) (*api.ReplicationController, error) {
	fake.updateMutex.Lock()
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		ctrl *api.ReplicationController
	}{ctrl})
	fake.recordInvocation("Update", []interface{}{ctrl})
	fake.updateMutex.Unlock()
	if fake.UpdateStub != nil {
		return fake.UpdateStub(ctrl)
	} else {
		return fake.updateReturns.result1, fake.updateReturns.result2
	}
}

func (fake *FakeReplicationControllerInterface) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeReplicationControllerInterface) UpdateArgsForCall(i int) *api.ReplicationController {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return fake.updateArgsForCall[i].ctrl
}

func (fake *FakeReplicationControllerInterface) UpdateReturns(result1 *api.ReplicationController, result2 error) {
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 *api.ReplicationController
		result2 error
	}{result1, result2}
}

func (fake *FakeReplicationControllerInterface) UpdateStatus(ctrl *api.ReplicationController) (*api.ReplicationController, error) {
	fake.updateStatusMutex.Lock()
	fake.updateStatusArgsForCall = append(fake.updateStatusArgsForCall, struct {
		ctrl *api.ReplicationController
	}{ctrl})
	fake.recordInvocation("UpdateStatus", []interface{}{ctrl})
	fake.updateStatusMutex.Unlock()
	if fake.UpdateStatusStub != nil {
		return fake.UpdateStatusStub(ctrl)
	} else {
		return fake.updateStatusReturns.result1, fake.updateStatusReturns.result2
	}
}

func (fake *FakeReplicationControllerInterface) UpdateStatusCallCount() int {
	fake.updateStatusMutex.RLock()
	defer fake.updateStatusMutex.RUnlock()
	return len(fake.updateStatusArgsForCall)
}

func (fake *FakeReplicationControllerInterface) UpdateStatusArgsForCall(i int) *api.ReplicationController {
	fake.updateStatusMutex.RLock()
	defer fake.updateStatusMutex.RUnlock()
	return fake.updateStatusArgsForCall[i].ctrl
}

func (fake *FakeReplicationControllerInterface) UpdateStatusReturns(result1 *api.ReplicationController, result2 error) {
	fake.UpdateStatusStub = nil
	fake.updateStatusReturns = struct {
		result1 *api.ReplicationController
		result2 error
	}{result1, result2}
}

func (fake *FakeReplicationControllerInterface) Delete(name string) error {
	fake.deleteMutex.Lock()
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		name string
	}{name})
	fake.recordInvocation("Delete", []interface{}{name})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(name)
	} else {
		return fake.deleteReturns.result1
	}
}

func (fake *FakeReplicationControllerInterface) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeReplicationControllerInterface) DeleteArgsForCall(i int) string {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return fake.deleteArgsForCall[i].name
}

func (fake *FakeReplicationControllerInterface) DeleteReturns(result1 error) {
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeReplicationControllerInterface) Watch(opts api.ListOptions) (watch.Interface, error) {
	fake.watchMutex.Lock()
	fake.watchArgsForCall = append(fake.watchArgsForCall, struct {
		opts api.ListOptions
	}{opts})
	fake.recordInvocation("Watch", []interface{}{opts})
	fake.watchMutex.Unlock()
	if fake.WatchStub != nil {
		return fake.WatchStub(opts)
	} else {
		return fake.watchReturns.result1, fake.watchReturns.result2
	}
}

func (fake *FakeReplicationControllerInterface) WatchCallCount() int {
	fake.watchMutex.RLock()
	defer fake.watchMutex.RUnlock()
	return len(fake.watchArgsForCall)
}

func (fake *FakeReplicationControllerInterface) WatchArgsForCall(i int) api.ListOptions {
	fake.watchMutex.RLock()
	defer fake.watchMutex.RUnlock()
	return fake.watchArgsForCall[i].opts
}

func (fake *FakeReplicationControllerInterface) WatchReturns(result1 watch.Interface, result2 error) {
	fake.WatchStub = nil
	fake.watchReturns = struct {
		result1 watch.Interface
		result2 error
	}{result1, result2}
}

func (fake *FakeReplicationControllerInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	fake.updateStatusMutex.RLock()
	defer fake.updateStatusMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.watchMutex.RLock()
	defer fake.watchMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeReplicationControllerInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ unversioned.ReplicationControllerInterface = new(FakeReplicationControllerInterface)
